baseDir: /home/<your_username>/path/to/repo
morphAddr:
  host: localhost
  port: 5050
enableMIDI: 1
enableGUI: 1
freqscopeActive: 0
debug: 1
mftDeviceName: Midi Fighter Twister
mftPortName: Midi Fighter Twister
numTracks: 3
